version: 2.1
jobs:
  build:
    working_directory: ~/payments
    docker:
      - image: circleci/openjdk:11-jdk-buster
    steps:
      - checkout
      - run: chmod +x ./mvnw
      - run: ./mvnw compile quarkus:dev
      