version: 2.1
jobs:
  build:
    working_directory: ~/payments
    docker:
      - image: circleci/openjdk:11-jdk-buster
    steps:
      - checkout
      - run: ./mvnw package -Dquarkus.package.type=uber-jar
      